### ISSUE TITLE
Configuring rabbitmq server / rabbitmq_sensu_password

### ISSUE THREAD

**Issue by tonyppe** [cmacrae/ansible-sensu#179] opened 2018-06-21 06:27 UTC
I would like to set non-default values here. I changed the variable of rabbitmq_sensu_password to something else other than sensu and then deployed the changes. I found that the deployment completed but it was broken. Checking the logs suggested the rabbitmq credentials were wrong. So I changed the json file back to the default password of sensu and restarted the services and all was working once again. I cannot see another variable which does the server side configuration of rabbitmq. 

Is it possible to set server side properties with this role here? If not then I would I need another role for that.

**Comment by jaredledvina** [comment] 2018-06-21 13:12
Hey @tonyppe!

So, I haven't personally tried changing `rabbitmq_sensu_password` but, looking through the code, it get's propagated to https://github.com/sensu/sensu-ansible/blob/master/tasks/rabbit.yml#L48-L56 which should be updating the actual user in RabbitMQ. Based on what you put here, it sounds like the password isn't getting propagated to the server config. 

Tracing that, if, `sensu_transport` is set to `rabbitmq` then we do this bit: https://github.com/sensu/sensu-ansible/blob/master/tasks/common.yml#L28-L41 where `sensu_rabbitmq_config` defaults to https://github.com/sensu/sensu-ansible/blob/master/defaults/main.yml#L67 and thus uses https://github.com/sensu/sensu-ansible/blob/master/templates/sensu-rabbitmq.json.j2 which is also using the `rabbitmq_sensu_password` variable here: https://github.com/sensu/sensu-ansible/blob/master/templates/sensu-rabbitmq.json.j2#L13

So, from what I'm seeing, we're properly configuring both the RabbitMQ side and the Sensu Server side. If changing the password back to the default worked in the Sensu config, then the step at https://github.com/sensu/sensu-ansible/blob/master/tasks/rabbit.yml#L48-L56 must not have actually updated the RabbitMQ password. 

I chekced out the docs on that `rabbitmq_user` module, and it looks like from https://docs.ansible.com/ansible/latest/modules/rabbitmq_user_module.html#rabbitmq-user-module, 

> To change the password of an existing user, you must also specify force=yes.

So, the 'cheap' answer is that we need to get `force: true` added to that task, but, looking just through the docs, every Ansible run is going to cause that entire user to be re-created which is not ideal. 

In the meantime, you can also use `rabbitmqctl change_password` to update the user in RabbitMQ (Docs: https://www.rabbitmq.com/rabbitmqctl.8.html#change_password ) that should also unblock.

**Comment by jaredledvina** [comment] 2018-06-21 13:17
Yeah, confirmed that the `rabbitmq_user` module with always delete and re-add the user if we use `force` https://github.com/ansible/ansible/blob/v2.4.4.0-1/lib/ansible/modules/messaging/rabbitmq_user.py#L285-L289 

Looks like there's quite a number of open PR's to fixup the module to be a bit nicer that have not gotten merged as well. 

EDIT:
Linking some PR's for the interested:
https://github.com/ansible/ansible/pull/19663/files (similar issue only for user permissions)
https://github.com/ansible/ansible/pull/22528/files
https://github.com/ansible/ansible/pull/27757/files

Seems like every submitter has left their PR there and most have gone stale. :(

**Comment by tonyppe** [comment] 2018-06-22 05:07
Thanks Jared! I will check more on this and come back here. For the moment this isn't really an issue; since I am still working out a plan then the defaults are fine. If I want to I can configure the server manually before doing the deploy if this is the case. 

thanks again for your help and thorough information!

**Comment by jaredledvina** [comment] 2018-06-22 12:44
Sounds good, at this time, I'm not finding anything from Ansible itself that will allow us to cleanly allow changing the password with the current `rabbitmq_user` module that also doesn't involve completely deleting and re-making the user. Let me know if you're able to work around this, and I've subscribed to the PR's that are already open to make this easier, if those get released, I'll follow up here.

**Comment by tonyppe** [comment] 2018-06-22 13:10
All good :) it's definitely not a blocker 👍😊

**Comment by jaredledvina** [comment] 2019-02-19 14:41
Sadly, Ansible has yet to address this upstream. If the above linked PR's are ever merged (some have been open for months now) we can do some work here. However, until then, I can't see a sane way that this can be supported within this role 😞 

I'm going to close this out, and am still subscribed to the above PR's such that if they do get released, we can revisit this. If anyone has any other ideas on how to support this, I encourage you to open a PR and we can discuss the options there.

**Closed as completed by jaredledvina** 2019-02-19 14:41 UTC
Labels: enhancement, help wanted, waiting-on-response
