### ISSUE TITLE
Implement automatic testing for this role with travis

### ISSUE THREAD

**Issue by RiRa12621** [cmacrae/ansible-sensu#40] opened 2016-08-25 08:21 UTC
it would be a good thing if there was the chance to enable testing this role automatically with travis

**Comment by jaredledvina** [comment] 2017-12-21 15:15
Closing as duplicate of https://github.com/sensu/sensu-ansible/issues/114 where I am attempting to get this to work!

**Closed as completed by jaredledvina** 2017-12-21 15:15 UTC
