### ISSUE TITLE
Failed to get information on remote file (/etc/sensu/ssl_generation/)

### ISSUE THREAD

**Issue by nertwork** [cmacrae/ansible-sensu#140] opened 2018-02-18 02:38 UTC
When running this for the first time on Ubuntu 16.04 server I noticed the issue of being unable to get information on remote file.

I noticed that as soon as I added the Sensu user's shell to /bin/bash from /bin/false it appeared to fix the issue.

**Comment by jaredledvina** [comment] 2018-02-18 02:39
Hey @nertwork, Can you comment with the error you got from the Ansible run? Currently, Travis is doing integration tests with 16.04 so, I'm surprised to see there's an issue. Thanks!

EDIT:
Also, which version of Sensu got installed? And which version of this role are you currently using?

**Comment by nertwork** [comment] 2018-02-18 04:25
Hey @jaredledvina, I'm using the default versions of Sensu and the most recent role allowed. The actual error that I get is below. I also ran across a similar error with the rabbitmq user. It's a default install of ubuntu as a VM.

```
fatal: [monitor.thenetwork.top]: FAILED! => {
    "changed": false, 
    "msg": "Failed to get information on remote file (/etc/sensu/ssl_generation/): OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 20
6\r\ndebug1: Reading configuration data /home/jfarr/.ssh/config\r\ndebug1: /home/jfarr/.ssh/config line 1: Applying options for *\r\ndebug3:
kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-gr
up1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names o
: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: /home/jfarr/.ssh/config line 90: Applying op
ions for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug
: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_
lient_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: 
ntering\r\ndebug3: mux_client_request_alive: done pid = 13896\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_cli
nt_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status 
rom master 1\r\nShared connection to monitor.thenetwork.top closed.\r\n"
}
```

**Comment by jaredledvina** [comment] 2018-02-18 14:55
Interesting, let me try locally and see what happens.

**Comment by jaredledvina** [comment] 2018-02-18 15:29
So, the task I think you're failing on is this block: https://github.com/sensu/sensu-ansible/blob/2.1.0/tasks/ssl_generate.yml#L15-L33

Where we use the `sensu` user on the `sensu_master` hosts to generate and manage the SSL certificates w/ the `ssl_certs.sh` script. I just tested locally on an Ubuntu 16.04 Vagrant VM and it worked for me:
```
TASK [../../sensu-ansible : Untar the ssl_certs tarball from sensuapp.org] *****
changed: [ubuntu16] => {"changed": true, "dest": "/etc/sensu/ssl_generation/", "extract_results": {"cmd": ["/bin/tar", "--extract", "-C", "/etc/sensu/ssl_generation/", "-f", "/tmp/ansible_i0NjF2/sensu_ssl_tool.tar"], "err": "", "out": "", "rc": 0}, "gid": 999, "group": "sensu", "handler": "TarArchive", "mode": "0755", "owner": "sensu", "size": 4096, "src": "/tmp/ansible_i0NjF2/sensu_ssl_tool.tar", "state": "directory", "uid": 999}

TASK [../../sensu-ansible : Generate SSL certs] ********************************
changed: [ubuntu16] => {"changed": true, "cmd": ["/bin/bash", "/etc/sensu/ssl_generation/sensu_ssl_tool/ssl_certs.sh", "generate"], "delta": "0:00:00.340408", "end": "2018-02-18 15:19:33.953644", "rc": 0, "start": "2018-02-18 15:19:33.613236", "stderr": "Generating a 2048 bit RSA private key\n....................................+++\n............+++\nunable to write 'random state'\nwriting new private key to './private/cakey.pem'\n-----\nGenerating RSA private key, 2048 bit long modulus\n..............+++\n.......+++\nunable to write 'random state'\ne is 65537 (0x10001)\nUsing configuration from openssl.cnf\nCheck that the request matches the signature\nSignature ok\nThe Subject's Distinguished Name is as follows\ncommonName            :ASN.1 12:'sensu'\norganizationName      :ASN.1 12:'server'\nCertificate is to be certified until Feb 17 15:19:33 2023 GMT (1825 days)\n\nWrite out database with 1 new entries\nData Base Updated\nunable to write 'random state'\nunable to write 'random state'\nGenerating RSA private key, 2048 bit long modulus\n.....+++\n...........................................................................................................................................+++\nunable to write 'random state'\ne is 65537 (0x10001)\nUsing configuration from openssl.cnf\nCheck that the request matches the signature\nSignature ok\nThe Subject's Distinguished Name is as follows\ncommonName            :ASN.1 12:'sensu'\norganizationName      :ASN.1 12:'client'\nCertificate is to be certified until Feb 17 15:19:33 2023 GMT (1825 days)\n\nWrite out database with 1 new entries\nData Base Updated\nunable to write 'random state'\nunable to write 'random state'", "stderr_lines": ["Generating a 2048 bit RSA private key", "....................................+++", "............+++", "unable to write 'random state'", "writing new private key to './private/cakey.pem'", "-----", "Generating RSA private key, 2048 bit long modulus", "..............+++", ".......+++", "unable to write 'random state'", "e is 65537 (0x10001)", "Using configuration from openssl.cnf", "Check that the request matches the signature", "Signature ok", "The Subject's Distinguished Name is as follows", "commonName            :ASN.1 12:'sensu'", "organizationName      :ASN.1 12:'server'", "Certificate is to be certified until Feb 17 15:19:33 2023 GMT (1825 days)", "", "Write out database with 1 new entries", "Data Base Updated", "unable to write 'random state'", "unable to write 'random state'", "Generating RSA private key, 2048 bit long modulus", ".....+++", "...........................................................................................................................................+++", "unable to write 'random state'", "e is 65537 (0x10001)", "Using configuration from openssl.cnf", "Check that the request matches the signature", "Signature ok", "The Subject's Distinguished Name is as follows", "commonName            :ASN.1 12:'sensu'", "organizationName      :ASN.1 12:'client'", "Certificate is to be certified until Feb 17 15:19:33 2023 GMT (1825 days)", "", "Write out database with 1 new entries", "Data Base Updated", "unable to write 'random state'", "unable to write 'random state'"], "stdout": "Generating SSL certificates for Sensu ...", "stdout_lines": ["Generating SSL certificates for Sensu ..."]}
```
And that's with the `sensu` user configured with:
```
root@ubuntu16:~# getent passwd sensu
sensu:x:999:999:Sensu Monitoring Framework:/opt/sensu:/bin/false
```

@nertwork - Is that error from https://github.com/sensu/sensu-ansible/blob/2.1.0/tasks/ssl_generate.yml#L17 or https://github.com/sensu/sensu-ansible/blob/2.1.0/tasks/ssl_generate.yml#L25? 

If it helps, I've pushed the Ubuntu 16.04 work here: https://github.com/sensu/sensu-ansible/compare/master...jaredledvina:feature/vagrant-gets-ubuntu16.04-vm?expand=1

**Comment by nertwork** [comment] 2018-02-18 20:24
@jaredledvina It's from both L17 and L25. I actually was unable to replicate this in a Vagrant test as well, so I'm not sure what's happening here but it's probably something local to either my Ansible install or the server I'm trying to deploy on. 

I'll see if I can come to some other resolution besides changing the users shell. I'll update if I find anything pertinent to the actual role.

Thanks you!

**Comment by jaredledvina** [comment] 2018-02-22 14:40
Hey @nertwork, yeah let me know if you figure it out as I'm generally curious what the issue is here. If there's anything we can adjust in this role as well, happy to take a look!

**Comment by jaredledvina** [comment] 2018-03-03 05:18
Hey @nertwork,

Just checking in here, were you able to come to a resolution for this issue?

**Comment by jaredledvina** [comment] 2018-03-17 01:56
Hey @nertwork,

I'll close this out but, let me know if you run into anything!

**Closed as completed by jaredledvina** 2018-03-17 01:56 UTC
Labels: waiting-on-response
